### ISSUE TITLE
WAVE presentation tests have no audio

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#110]
The following tests are for a WAVE presentation but now don't have any audio.

Regular Playback of a CMAF Presentation
![image](https://user-images.githubusercontent.com/8490792/234547272-a834c817-df6c-4449-a51f-cb5f95c3f90b.png)
Random Access of a WAVE Presentation
![image](https://user-images.githubusercontent.com/8490792/234548355-1bff0041-8b45-4fb1-8465-dea0339d9126.png)

t1 is not formally required to have audio but it did in the beginning.
We don't have an AVC test stream with audio except for the long duration one.

**Comment by jpiesing** [comment]
See also https://github.com/cta-wave/Test-Content-Generation/issues/62

**Comment by rcottingham** [comment]
Hi Jon, this should be the PN audio. AAC content is now ready to be uploaded to Akamai. We will provide the URL to Fraunhofer when it's available, who can then update the test.

**Comment by rcottingham** [comment]
Audio to use for these two tests is located here: https://dash-large-files.akamaized.net/WAVE/vectors/releases/1/caac_sets/aac_lc/at1/

**Comment by FritzHeiden** [comment]
Tests now have audio via audio only aac mpd

**Comment by gitwjr** [comment]
Relates to DPCTF Tests #111 . This is on @FritzHeiden list of tasks when checking splicing tests.

**Comment by jpiesing** [comment]
This is an HbbTV originated issue which I had marked resolved. It's OK if the test was recorded without audio but if the test actually doesn't have any audio then that's a blocker.

**Comment by jpiesing** [comment]
@louaybassbouss @FritzHeiden Can this now be marked as fixed and closed? If so, please do it.

**Comment by FritzHeiden** [comment]
This is fixed.

**Comment by Lis-TV** [comment]
Hi.
Actually it is not fixed. I see no audio in my tests in both master and hbbtv-tests branches.
Please look to https://github.com/cta-wave/dpctf-tests/blob/hbbtv-tests/generated/tests.json , there is an empty array audio set for random-access-of-a-wave-presentation__t1.html.

**Comment by FritzHeiden** [comment]
@Lis-TV This issue is regarding WAVE DPCTF tests. In HbbTV context the content used in the tests is different. Afaic, the random-access-of-a-wave-presentation__t1.html test is not specified to have an audio track.

**Comment by jpiesing** [comment]
> @Lis-TV This issue is regarding WAVE DPCTF tests. In HbbTV context the content used in the tests is different. Afaic, the random-access-of-a-wave-presentation__t1.html test is not specified to have an audio track.

I'm really confused, the same content should be used in all tests or everything gets unmanagable.

A WAVE presentation **by definition** has an audio track.

**Comment by FritzHeiden** [comment]
> I'm really confused, the same content should be used in all tests or everything gets unmanagable.
> 
> A WAVE presentation **by definition** has an audio track.

I am sorry, wasn't aware of that. All I did in the case of the HbbTV test cases was to follow the specification for each tests xml file (`tech.cta.wave.dpctf_AVC-25-50-PLAYBACK_0310` in the case of `random-access-of-a-wave-presentation__t1.html`). Unfortunately, I am not sure where to find these, as I collected all information I needed from them in a spreadsheet for better overview. 

According to my spreadsheet the only content for the mentioned test case was supposed to be `cfhd_sets/12.5_25_50/t1/stream.mpd`, which didn't have any audio in the latest version of the content at that point in time. (https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1/2023-04-28/stream.mpd)

If it is preferred to use the same template-content combination in any place I will fix this of course.

**Comment by Lis-TV** [comment]
@FritzHeiden from my perspective, please add audio to  random-access-of-a-wave-presentation__t1.html.

**Comment by FritzHeiden** [comment]
@Lis-TV The hbbtv branch is now merged into main. There is no longer a subset for hbbtv test. Rather required test for hbbtv should be select from the main set. In the main set the mentioned test has audio content.
