### ISSUE TITLE
DPCAT - status event at the end of test and status event for truncated test

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#87]
I would like to get status event from test runner confirmed at the end of test so that OF can process it correctly.
What will be expected at the end of playback and at the end of the test on test runner?
Can you confirm the following please?

- For tests other than the truncated test, status will changes as follows: 
playing - ended - finshed
- For truncated test, status will changes as follows: 
playing - ended - playing - ended - finished

**Comment by yanj-github** [comment]
Checking the DPCAT branch of the most up to date code:

- For tests other than the truncated test, status will changes as follows from playing then straight to finshed without ended.
Is this what is expected please? I dont have objection but just need to confrim to make changes on OF accordingly.

- Unable to check for truncated test, test doesnt run till the end https://github.com/cta-wave/dpctf-tests/issues/83
Can you confirm "playing - ended - playing - ended - finished" is intended for  truncated test please?

**Comment by louaybassbouss** [comment]
@yanj-github the `finished` event is the last event fired to declare that the test is completed and the runner moves to the next test. Other events are fired by the underlying video element and since all tests waits until the content is played until the end, you should always see `ended` event before `finished`.  

Please try the truncate test again after the fix in #83

**Comment by yanj-github** [comment]
Thanks @louaybassbouss currently I dont see ended event I will check it again withe the latest change.

**Comment by FritzHeiden** [comment]
@yanj-github Can you elaborate on how you are trying to receive these events? I used the events API and there I get playing, ended and completed events. For truncate test, there is only one ended event, as the first switching set does not play until the end.

**Comment by yanj-github** [comment]
@FritzHeiden We would like to have a status signaled when 1st presentation finished such as "ended" and a different status signaled at the end of test which is "finished". Any problems please?

**Comment by FritzHeiden** [comment]
Understood. I will implement an event for changing presentations/switching sets.

**Comment by yanj-github** [comment]
Thank @FritzHeiden I just noticed there are addtional frames rendered between end do 1st presentation and starting of the 2nd one. Can you look at it together with this issue please?

**Comment by FritzHeiden** [comment]
@yanj-github There is now a playback event of type 'representation_changed'

**Comment by yanj-github** [comment]
@louaybassbouss  and @dsilhavy as we now added "second_playout" and "second_playout_switching_time" the spec defined it not alien with these parameters anymore. Can any of you kinldy explain how we should see these to be rendered please?
Are we expecting the 1st representation at "second_playout_switching_time" then 2nd representation presented based on "second_playout" from frame 1 to the end of "second_playout"?
Or 1st representation should finish its defined "playout" then 2nd representation presented based on "second_playout" from frame 1 to the end of "second_playout"?

**Comment by FritzHeiden** [comment]
I can confirm this. There seems to be an issue with the import script. Will work on a fix

**Comment by FritzHeiden** [comment]
@yanj-github I pushed a fix to the dpctf-tests repository. You should now see the event.

**Comment by yanj-github** [comment]
@FritzHeiden  I still cannot see this event I can see playing then waiting then buffering playing...
The contents presented are 0-5 seconds 1st conent and then it on hold at frame 1 of 1st conent and play 1st content from frame 1-5 then it changed content play the 2nd content from 2 seconds to 5 seconds. 
Also I noticed that I am unable to run local test online tests are fine.

**Comment by FritzHeiden** [comment]
@yanj-github Did you rebuild the image with `--reload-tests` and `--tests-branch dpcat` ?

**Comment by yanj-github** [comment]
> @yanj-github Did you rebuild the image with `--reload-tests` and `--tests-branch dpcat` ?

Yes I did, I have removed everything and did a clean set up. 
Have you checked on your end please? It can be device issue as well.

**Comment by FritzHeiden** [comment]
Just rebuilt the image and I can see the event

![image](https://user-images.githubusercontent.com/9076000/196423170-ed5bc74c-6bda-406b-899c-38b561ac2ac7.png)

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I will try on different device.

**Comment by yanj-github** [comment]
@FritzHeiden  I have noticed the locol test doesnt work I am unable to set up to run on device with online access. Can you kindly help to fix local tests please? Then I will be able to test this on a TV with different browser.
Just an update I have tried this on both firefox and chorme I cannot see the event. I have tried a clean build as well. 
... ...
889,,,,,playing,play,4.932455,12,,
890,A1,5240.0,131,25.0,,,,,,
890,,,,,playing,play,4.932455,12,,
891,A1,5240.0,131,25.0,,,,,,
892,A1,5240.0,131,25.0,,,,,,
893,A1,5240.0,131,25.0,,,,,,
893,,,,,buffering,play,0.0,11,,
894,A1,5240.0,131,25.0,,,,,,
894,,,,,buffering,play,0.0,11,,
895,A1,5240.0,131,25.0,,,,,,
895,,,,,buffering,play,0.0,11,,
896,A1,5240.0,131,25.0,,,,,,
896,,,,,buffering,play,0.0,11,,
897,A1,5240.0,131,25.0,,,,,,
898,A1,5240.0,131,25.0,,,,,,
898,,,,,waiting,play,0.0,18,,
899,A1,5240.0,131,25.0,,,,,,
899,,,,,waiting,play,0.0,18,,
900,A1,5240.0,131,25.0,,,,,,
900,,,,,waiting,play,0.0,18,,
901,A1,5240.0,131,25.0,,,,,,
901,,,,,waiting,play,0.0,18,,
902,A1,5240.0,131,25.0,,,,,,
902,,,,,waiting,play,0.0,18,,
903,AD-A1,40.0,1,25.0,,,,,,
903,A1,5240.0,131,25.0,,,,,,
903,,,,,waiting,play,0.0,18,,
904,A1,5240.0,131,25.0,,,,,,
904,AD-A1,40.0,1,25.0,,,,,,
904,,,,,waiting,play,0.0,18,,
905,AD-A1,40.0,1,25.0,,,,,,
905,,,,,waiting,play,0.0,18,,
906,AD-A1,40.0,1,25.0,,,,,,
906,,,,,waiting,play,0.0,18,,
907,AD-A1,40.0,1,25.0,,,,,,
908,AD-A1,40.0,1,25.0,,,,,,
908,,,,,waiting,play,0.0,22,,
909,AD-A1,40.0,1,25.0,,,,,,
909,,,,,waiting,play,0.0,22,,
910,AD-A1,40.0,1,25.0,,,,,,
910,,,,,waiting,play,0.0,22,,
911,AD-A1,40.0,1,25.0,,,,,,
912,AD-A1,40.0,1,25.0,,,,,,
912,,,,,playing,play,0.0,17,,
913,AD-A1,80.0,2,25.0,,,,,,
913,AD-A1,40.0,1,25.0,,,,,,
913,,,,,playing,play,0.0,17,,
914,AD-A1,40.0,1,25.0,,,,,,
914,AD-A1,80.0,2,25.0,,,,,,
914,,,,,playing,play,0.0,17,,
... ...

**Comment by yanj-github** [comment]
@louaybassbouss  and @FritzHeiden is there any update to this ticket please?

**Comment by FritzHeiden** [comment]
> @FritzHeiden I have noticed the local test doesnt work I am unable to set up to run on device with online access. Can you kindly help to fix local tests please? Then I will be able to test this on a TV with different browser. 

I cannot confirm this, everything works fine for me.

> Just an update I have tried this on both firefox and chorme I cannot see the event. I have tried a clean build as well. 

I noticed you need the event in the QR code. The event I implemented uses the events API. I already implemented the event in the QR code, however, a regression with another test still blocks me from pushing the update.

**Comment by FritzHeiden** [comment]
@yanj-github I pushed the update now. Please check if everything works for you

**Comment by yanj-github** [comment]
Thanks @FritzHeiden for the quick manual check I can see event action = representation_changed. I will do some further investigate on OF later. I will close this issue when checks done on OF, I will keep it posted.

**Comment by yanj-github** [comment]
Action detected is "representation_change" not "representation_changed" which is fine with me. 
Closing this issue now.
